Fix missing import in `amici/petab/petab_import.py` (#2342)
fixes 
```
Traceback (most recent call last):
  File "//./mnt/src/optimize.py", line 557, in <module>
    model, model_petab_problem = _model_import(
  File "/mnt/src/util.py", line 44, in _model_import
    model = amici.petab_import.import_petab_problem(
  File "/usr/local/lib/python3.10/dist-packages/amici/petab/petab_import.py", line 79, in import_petab_problem
    warn(
NameError: name 'warn' is not defined
```