Fix HDF5 OSX intermediate group creation errors (#1741)
Still not sure what the original problem was, but going through the HDF5 C++ API seems to fix the following error occurring in `amici::hdf5::hdf5CreateGroup` with recent HDF5 versions on OSX: 
```
>       return _amici.writeSolverSettingsToHDF5(*args)
E       RuntimeError: Failed to create group in hdf5CreateGroup: ssettings

../sdist/amici/amici.py:6129: RuntimeError
----------------------------- Captured stderr call -----------------------------
HDF5-DIAG: Error detected in HDF5 (1.10.8) thread 0:
  #000: H5Plcpl.c line 152 in H5Pset_create_intermediate_group(): can't find object for ID
    major: Object atom
    minor: Unable to find atom information (already closed?)
  #001: H5Pint.c line 3805 in H5P_object_verify(): property list is not a member of the class
    major: Property lists
    minor: Unable to register new atom
  #002: H5Pint.c line 3756 in H5P_isa_class(): not a property list
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.10.8) thread 0:
  #000: H5G.c line 288 in H5Gcreate2(): not link creation property list
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: H5Pint.c line 3756 in H5P_isa_class(): not a property list
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.10.8) thread 0:
  #000: H5P.c line 1488 in H5Pclose(): not a property list
    major: Invalid arguments to routine
    minor: Inappropriate type
``` 

`H5::LinkCreatPropList::setCreateIntermediateGroup` was only added in HDF5 1.10.6, but current Ubuntu LTS still comes with HDF5 1.10.4. Therefore we still need to keep the C version.