Speedup modelname.cpp compilation by using char arrays instead of std::string (#1137)
Follow-up to #1105

tested with icpc (ICC) 19.0.5.281 20190815; -O3:

> Elapsed (wall clock) time (h:mm:ss or m:ss): 0:01.17
> Maximum resident set size (kbytes): 249984

before, terminated at:
> Elapsed (wall clock) time (h:mm:ss or m:ss): 2:19:33
> Maximum resident set size (kbytes): 443383356
> Fatal compilation error: Out of memory asking for 18446744072184442880.