Miscellaneous fixes, python packaging and python API improvements  (#327)
* fix(swig) Make enums and constants available in python

* fix(python) edata is regular pointer, not unique_ptr here

* refactor(cmake)

* fix(python) Fix linking order. Fix C++ standard.

* feature(python) Add verbosity switch for model compilation

* feature(python) Add verbosity switch for sbml2amici

* fix(python) Make swig aware of enums in time to generate appropriate mappers

* doc(python) Extend python API steadystate example. Change to notebook.

* fix(python) Check edata type. Here it can be regular or unique pointer

* fix(python) Check edata type. Here it can be regular or unique pointer

* doc(python) Cleanup notebook

* doc(python) Add finite differences sensitivity check to example

* feature(python) Allow blas selection for amici base package installation via environment variables #320

* doc(python) Add model info to example

* Fix(python) Fix negative log likelihood

* Feature(python) Expose std::vector<amici::AMICI_parameter_scaling> as ParameterScalingVector

* doc(core) Fix dimension order

* ci(python) Run gradient check for example models (don't fail test yet)

* ci(travis) Install scipy

* build(cmake) CMake cleanup

* ci(travis) Test creating and installing sdist on ci server

* fix(python) Increase chances of finding swig on OSX #320

* ci(python) Don't use pyenv pip which is broken by recent update

  File '/opt/pyenv/versions/3.6/bin/pip3', line 7, in <module>
    from pip import main
ImportError: cannot import name 'main'

* fix(python) Catch hdf5.cpp not found problem #320

* doc(doxygen) Ignore autogenerated file

* fix(python) Set sensitivity flag for dydp (thx FFroehlich)

* feature(python) Exception on package setup failure

* fix(python) Fix sx summation. Fixes sx gradient check (thx FFroehlich)

* fix(python) fix sy computation in python generated models

* Fix typo, rewrap models, remove notebook test code