Fix CMake using incorrect Python library for building model extension (#2220)
This fixes a bug where a model extension would be built for an incorrect Python version. If there is a newer Python version available than the one in use during model import, CMake would incorrectly used the newer version. This results in not so informative errors like:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/model_name/model_name.py", line 12, in <module>
    import _model_name
ModuleNotFoundError: No module named '_model_name'
```

Fixed here by explicitly setting the Python executable that is used to find the matching libraries.