Upgrade to sundials 5.7.0 (#1392)
* Upgrade to sundials 5.7.0

* Disable shared libs

* No __attribute__ ((__deprecated__)) for msvc

* Revert "No __attribute__ ((__deprecated__)) for msvc"

This reverts commit 8dfac2b8aa5d12e39aa2e70f3ccbf5726cab242c.

* No __attribute__ ((__deprecated__)) for msvc

* Fix error C2059: syntax error: 'constant'?

* DBG

* d'oh

* ..

* SUNDIALS_DEPRECATED

* SUNDIALS_DEPRECATED for __GNUC__

* update error code for singular jacobian and add static assert

Co-authored-by: Fabian Fröhlich <fabian_froehlich@hms.harvard.edu>
Co-authored-by: FFroehlich <fabian@schaluck.com>