ci(python) Don't use pyenv pip which is broken by recent update
  File '/opt/pyenv/versions/3.6/bin/pip3', line 7, in <module>
    from pip import main
ImportError: cannot import name 'main'