Update documentation stack (#1527)
* RTD with Ubuntu20.04
* Recent doxygen with various bugfixed
* Updates sphinx, breathe, ... 
* Stick to Python 3.8 on RTD, because with 3.9:
```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/amici/envs/1527/lib/python3.9/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/home/docs/checkouts/readthedocs.org/user_builds/amici/envs/1527/lib/python3.9/site-packages/sphinx/application.py", line 237, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amici/envs/1527/lib/python3.9/site-packages/sphinx/application.py", line 393, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amici/envs/1527/lib/python3.9/site-packages/sphinx/registry.py", line 442, in load_extension
    metadata = setup(app)
  File "/home/docs/checkouts/readthedocs.org/user_builds/amici/envs/1527/lib/python3.9/site-packages/recommonmark/__init__.py", line 9, in setup
    from .parser import CommonMarkParser
  File "/home/docs/checkouts/readthedocs.org/user_builds/amici/envs/1527/lib/python3.9/site-packages/recommonmark/parser.py", line 9, in <module>
    from commonmark import Parser
  File "/home/docs/checkouts/readthedocs.org/user_builds/amici/envs/1527/lib/python3.9/site-packages/commonmark/__init__.py", line 4, in <module>
    from commonmark.main import commonmark
  File "/home/docs/checkouts/readthedocs.org/user_builds/amici/envs/1527/lib/python3.9/site-packages/commonmark/main.py", line 14, in <module>
    from commonmark.blocks import Parser
  File "/home/docs/checkouts/readthedocs.org/user_builds/amici/envs/1527/lib/python3.9/site-packages/commonmark/blocks.py", line 5, in <module>
    from commonmark import common
  File "/home/docs/checkouts/readthedocs.org/user_builds/amici/envs/1527/lib/python3.9/site-packages/commonmark/common.py", line 14, in <module>
    HTMLunescape = html.parser.HTMLParser().unescape
AttributeError: 'HTMLParser' object has no attribute 'unescape'

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/amici/envs/1527/lib/python3.9/site-packages/commonmark/common.py", line 14, in <module>
    HTMLunescape = html.parser.HTMLParser().unescape
AttributeError: 'HTMLParser' object has no attribute 'unescape'
```