Require sympy<1.9
Until pysb symbols are deepcopy-able with sympy 1.9

Currently results in:
```
cls = <class 'pysb.core.Parameter'>, args = ('PROT_0', 2150901)
kwargs = {'commutative': True, 'complex': True, 'composite': False, 'even': False, ...}

    def __newobj_ex__(cls, args, kwargs):
        """Used by pickle protocol 4, instead of __newobj__ to allow classes with
        keyword-only arguments to be pickled correctly.
        """
>       return cls.__new__(cls, *args, **kwargs)
E       TypeError: __new__() got an unexpected keyword argument 'real'
```